import { useEffect, useMemo, useState } from "react";
import { z } from "zod";
import { ClipboardCheck } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useApi } from "@/context/ApiProvider";
import { PRODUCTION_ENDPOINTS } from "@/lib/production";
import type { ProductionTaskRecord } from "./ProductionTaskPanel";
const schema = z.object({ task: z.coerce.number().min(1), update_date: z.string().min(1, "تاریخ گزارش را وارد کنید"), progress_percent: z.coerce.number().min(0).max(100), description: z.string().min(2, "گزارش را وارد کنید") });
type Props = { open: boolean; task: ProductionTaskRecord | null; onOpenChange: (open: boolean) => void; onSaved: () => void };
export function ProductionTaskUpdatePanel({ open, task, onOpenChange, onSaved }: Props) { const api = useApi(); const today = useMemo(() => new Date().toISOString().slice(0, 10), []); const [form, setForm] = useState({ task: "", update_date: today, progress_percent: "0", description: "" }); const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); useEffect(() => { if (!open || !task) return; setForm({ task: String(task.id), update_date: today, progress_percent: String(task.progress_percent || 0), description: "" }); setErrors({}); }, [open, task, today]); const set = (k: string, v: string) => { setForm((p) => ({ ...p, [k]: v })); setErrors((p) => ({ ...p, [k]: "" })); }; const submit = async (e: React.FormEvent) => { e.preventDefault(); const result = schema.safeParse(form); if (!result.success) { const next: Record<string, string> = {}; result.error.errors.forEach((err) => { next[err.path[0] as string] = err.message; }); setErrors(next); return; } setBusy(true); try { const res = await api.post(PRODUCTION_ENDPOINTS.taskUpdates, result.data); if (!res.ok) { toast.error("ثبت گزارش ناموفق بود"); return; } toast.success("گزارش پیشرفت ثبت شد"); onOpenChange(false); onSaved(); } catch (err) { console.error(err); toast.error("خطا در ارتباط با سرور"); } finally { setBusy(false); } }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent dir="rtl" className="max-w-xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-primary" />گزارش پیشرفت تولید</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="rounded-lg bg-muted/40 px-4 py-3 text-sm text-muted-foreground">{task?.title}</div><div className="grid gap-3 sm:grid-cols-2"><Field label="تاریخ گزارش" error={errors.update_date}><Input type="date" value={form.update_date} onChange={(e) => set("update_date", e.target.value)} /></Field><Field label="درصد پیشرفت" error={errors.progress_percent}><Input type="number" min={0} max={100} value={form.progress_percent} onChange={(e) => set("progress_percent", e.target.value)} /></Field></div><Field label="کارهای انجام‌شده" error={errors.description}><Textarea rows={4} value={form.description} onChange={(e) => set("description", e.target.value)} /></Field><DialogFooter className="gap-2 sm:justify-start"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>انصراف</Button><Button type="submit" disabled={busy} className="gradient-primary">ثبت گزارش</Button></DialogFooter></form></DialogContent></Dialog>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}{error ? <p className="text-xs text-destructive">{error}</p> : null}</div>; }
