import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, ClipboardCheck, Edit2, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { useApi } from "@/context/ApiProvider";
import { formatNumber } from "@/lib/departments";
import { choiceLabel, RND_CATEGORIES, RND_ENDPOINTS, RND_TASK_PRIORITIES, RND_TASK_STATUSES } from "@/lib/rnd";
import type { RndTaskRecord } from "./RndTaskPanel";

type Props = { year: string; month: string; period: string; refreshKey: number; onChanged: () => void; onEditTask?: (item: RndTaskRecord) => void; onUpdateTask?: (item: RndTaskRecord) => void };
type PaginatedResponse = { count: number; next: string | null; previous: string | null; results: any[] };
const PAGE_SIZE = 10;
export function RndTaskList({ year, month, period, refreshKey, onChanged, onEditTask, onUpdateTask }: Props) {
  const api = useApi(); const [items, setItems] = useState<RndTaskRecord[]>([]); const [loading, setLoading] = useState(true); const [page, setPage] = useState(1); const [count, setCount] = useState(0); const [next, setNext] = useState<string | null>(null); const [previous, setPrevious] = useState<string | null>(null); const totalPages = Math.max(1, Math.ceil(count / PAGE_SIZE));
  useEffect(() => { setPage(1); }, [year, month, period]);
  useEffect(() => { let alive = true; setLoading(true); const params = new URLSearchParams({ year, month, period, page: String(page) }); api.get(`${RND_ENDPOINTS.tasks}?${params.toString()}`).then((res) => { if (!alive) return; const body = res.body as PaginatedResponse | any[]; if (Array.isArray(body)) { setItems(body); setCount(body.length); setNext(null); setPrevious(null); } else { setItems(body?.results || []); setCount(Number(body?.count || 0)); setNext(body?.next || null); setPrevious(body?.previous || null); } setLoading(false); }).catch(() => alive && setLoading(false)); return () => { alive = false; }; }, [api, year, month, period, refreshKey, page]);
  const remove = async (id: number) => { if (!confirm("این کار حذف شود؟")) return; const res = await api.delete(`${RND_ENDPOINTS.tasks}${id}/`); if (res.ok) { toast.success("کار حذف شد"); setItems((prev) => prev.filter((x) => x.id !== id)); onChanged(); } else toast.error("خطا در حذف کار"); };
  if (loading) return <div className="card-elegant grid place-items-center rounded-2xl py-12 text-muted-foreground animate-pulse">در حال بارگذاری...</div>;
  if (!items.length) return <div className="card-elegant grid place-items-center rounded-2xl py-12 text-center"><p className="text-muted-foreground">برای این دوره هنوز کاری ثبت نشده است.</p></div>;
  return <div className="space-y-4"><div className="space-y-2">{items.map((item) => <TaskRow key={item.id} item={item} onEdit={() => onEditTask?.(item)} onUpdate={() => onUpdateTask?.(item)} onDelete={() => remove(item.id)} />)}</div><div className="flex flex-col gap-3 rounded-2xl border border-border/70 bg-card/70 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs text-muted-foreground">صفحه <span className="num-fa font-semibold text-foreground">{formatNumber(page)}</span> از <span className="num-fa font-semibold text-foreground">{formatNumber(totalPages)}</span><span className="mx-2 text-border">|</span>مجموع کارها: <span className="num-fa font-semibold text-foreground">{formatNumber(count)}</span></div><div className="flex items-center gap-2"><Button type="button" variant="outline" size="sm" disabled={!previous || page <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}><ChevronRight className="ml-1 h-4 w-4" />قبلی</Button><Button type="button" variant="outline" size="sm" disabled={!next || page >= totalPages} onClick={() => setPage((p) => p + 1)}>بعدی<ChevronLeft className="mr-1 h-4 w-4" /></Button></div></div></div>;
}
function TaskRow({ item, onEdit, onUpdate, onDelete }: { item: RndTaskRecord; onEdit: () => void; onUpdate: () => void; onDelete: () => void }) { const categoryLabel = item.category_label ?? choiceLabel(RND_CATEGORIES, item.category); const statusLabel = item.status_label ?? choiceLabel(RND_TASK_STATUSES, item.status); const priorityLabel = item.priority_label ?? choiceLabel(RND_TASK_PRIORITIES, item.priority); return <div className="card-elegant rounded-2xl border border-border/70 bg-card/80 p-4 transition hover:-translate-y-0.5 hover:bg-muted/25"><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1 space-y-2"><div className="font-semibold text-foreground">{item.title}</div><div className="text-sm text-muted-foreground">{categoryLabel} · {item.start_date} تا {item.end_date} · {statusLabel} · اولویت {priorityLabel}</div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${item.progress_percent}%` }} /></div><div className="num-fa text-xs text-muted-foreground">پیشرفت: {formatNumber(item.progress_percent)}٪</div></div><div className="flex shrink-0 flex-wrap justify-end gap-1"><Button type="button" variant="ghost" size="icon" onClick={onUpdate} title="ثبت گزارش"><ClipboardCheck className="h-4 w-4 text-primary" /></Button><Button type="button" variant="ghost" size="icon" onClick={onEdit}><Edit2 className="h-4 w-4" /></Button><Button type="button" variant="ghost" size="icon" onClick={onDelete}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div></div>; }
